import homeRoute from '@/routes/home-page';
import hospitalRoute from '@/routes/hospital';
import userRoute from '@/routes/user';
import patientRoute from '@/routes/patient';
import examinationRoute from '@/routes/examination';
import emrRoute from '@/routes/emr';
import presentingComplaintRoute from '@/routes/presenting-complaint';
import trimesterRoute from '@/routes/trimester';
import currentPregnancyRoute from '@/routes/current-pregnancy';
import obstetricHistoryRoute from '@/routes/obstetric-history';
import gynecologicalHistoryRoute from '@/routes/gynecological-history';
import medicalHistoryRoute from '@/routes/medical-history';
import surgicalHistoryRoute from '@/routes/surgical-history';
import familyHistoryRoute from '@/routes/family-history';
import personalHistoryRoute from '@/routes/personal-history';
import socioEconomicHistoryRoute from '@/routes/socio-economic-history';
import vitalsRoute from '@/routes/vitals';
import followupQuestionsRoute from '@/routes/followup-questions';
import filesRoute from '@/routes/files';
import generatePresignedUrls from '@/routes/generate-presigned-urls';

export const registerRoutes = () => {
  homeRoute.getRoutingPath();
  generatePresignedUrls.getRoutingPath();
  emrRoute.getRoutingPath();
  presentingComplaintRoute.getRoutingPath();
  trimesterRoute.getRoutingPath();
  currentPregnancyRoute.getRoutingPath();
  obstetricHistoryRoute.getRoutingPath();
  gynecologicalHistoryRoute.getRoutingPath();
  medicalHistoryRoute.getRoutingPath();
  surgicalHistoryRoute.getRoutingPath();
  familyHistoryRoute.getRoutingPath();
  personalHistoryRoute.getRoutingPath();
  socioEconomicHistoryRoute.getRoutingPath();
  vitalsRoute.getRoutingPath();
  followupQuestionsRoute.getRoutingPath();
  filesRoute.getRoutingPath();
  examinationRoute.getRoutingPath();
  hospitalRoute.getRoutingPath();
  userRoute.getRoutingPath();
  patientRoute.getRoutingPath();
};
