steps:
# Build The Image
- id: "build-docker-image"
  name: "gcr.io/cloud-builders/docker"
  args:
  - "build"
  - "-t"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
  - "${_BUILD_DIR}"
# Push The Image
- id: "push-docker-image"
  name: "gcr.io/cloud-builders/docker"
  args:
  - "push"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
# Update The Cloud Run Service
- id: "update-cloud-run-service"
  name: "gcr.io/cloud-builders/gcloud"
  args:
  - "run"
  - "services"
  - "update"
  - "${_SERVICE_NAME}"
  - "--image"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
  - "--region"
  - "${_REGION}"
# Define the images built by this build
images:
- "us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$SHORT_SHA"
# Substitutions for custom values
substitutions:
  _REPOSITORY: awaaz-core-server
  _IMAGE_NAME: server
  _BUILD_DIR: web-server
  _SERVICE_NAME: core-server-${BRANCH_NAME}
  _REGION: asia-southeast1
