import { z } from 'zod';

export const examinationDetailsSchema = z.object({
  generationTime: z.date(),
  emrId: z.string().uuid(),
  doctorId: z.string().uuid(),
  modifiedDoctorId: z.string().uuid().optional(),
  updatedAt: z.date().optional(),
  bloodPressure: z.string().optional(),
  pr: z.string().optional(),
  rr: z.string().optional(),
  temperature: z.string().optional(),
  bilateralPedalEdema: z.string().optional(),
  clubbing: z.string().optional(),
  jaundice: z.string().optional(),
  koilonychia: z.string().optional(),
  lymphNodes: z.string().optional(),
  pallor: z.string().optional(),
  spine: z.string().optional(),
  nippleDeformity: z.string().optional(),
  nippleDischarge: z.string().optional(),
  sizeComparison: z.string().optional(),
  swelling: z.string().optional(),
  abdominalWallEdema: z.string().optional(),
  estimatedFetalWeight: z.string().optional(),
  fetalHeartRate: z.string().optional(),
  fundalHeight: z.string().optional(),
  hernialOrfices: z.string().optional(),
  lie: z.string().optional(),
  liquor: z.string().optional(),
  presentation: z.string().optional(),
  prominentVeins: z.string().optional(),
  pulsations: z.string().optional(),
  scarTenderness: z.string().optional(),
  shapeOfAbdomen: z.string().optional(),
  striae: z.string().optional(),
  umbilicus: z.string().optional(),
  perSpeculumFindings: z.string().optional(),
  perVaginalFindings: z.string().optional(),
  cns: z.string().optional(),
  cvs: z.string().optional()
});
